const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const {catalogBase} = require('./browser-fixture.cjs');
const catalogScreenCount = JSON.parse(require('node:fs').readFileSync(process.env.CATALOG_SNAPSHOT || 'site/data.json', 'utf8')).screens.length.toLocaleString();

(async () => {
  const browser = await chromium.launch({headless:true, channel:process.env.PLAYWRIGHT_CHANNEL || 'chrome'});
  const page = await browser.newPage();
  const base = await catalogBase(page);
  if (process.env.CATALOG_SNAPSHOT) await page.route('**/data.json', route => route.fulfill({contentType:'application/json',body:require('node:fs').readFileSync(process.env.CATALOG_SNAPSHOT,'utf8')}));
  try {
    await page.goto(base + '#flows');
    await page.locator('.collection-card').first().waitFor();
    assert.equal(await page.locator('.collection-card').count(), 7);
    assert.equal(await page.locator('.collection-flows').first().locator('.collection-previews img').count(), 4);
    const flowTitle = await page.locator('.collection-card').first().locator('.collection-title').textContent();
    await page.locator('.collection-card').first().locator('[data-save-collection]').click();
    assert.equal(await page.locator('.collection-card').first().locator('[data-save-collection]').getAttribute('aria-pressed'), 'true');
    await page.locator('.collection-card').first().getByRole('button', {name:/Open/}).click();
    assert.match(await page.locator('#viewerContent').textContent(), /Listing collection · interaction order unverified/);
    assert.equal(await page.locator('.screen-thumbnails button').count(), 4);
    const title = await page.locator('#viewerTitle').textContent();
    await page.keyboard.press('ArrowRight');
    assert.equal(await page.locator('#viewerTitle').textContent(), title);
    assert.match(await page.locator('.screen-context').textContent(), /interaction order unverified/);
    await page.locator('#viewerContent [data-save]').first().click();
    assert.equal(await page.locator('#viewerContent [data-save]').first().getAttribute('aria-pressed'), 'true');
    await page.keyboard.press('Escape');
    await page.locator('#viewer').waitFor({state:'hidden'});
    await page.getByRole('link', {name:'Saved board', exact:true}).click();
    await page.waitForFunction(() => document.querySelector('#title').textContent === 'Saved board');
    const savedFlow = page.locator('.collection-card .collection-title').filter({hasText:flowTitle});
    await savedFlow.waitFor();
    assert.equal(await page.locator('.collection-card').count(), 1);
    const [boardDownload] = await Promise.all([page.waitForEvent('download'), page.locator('#export').click()]);
    const boardExport = JSON.parse(require('node:fs').readFileSync(await boardDownload.path(), 'utf8'));
    assert.equal(boardExport.records.length, 1);
    assert.equal(boardExport.collections.length, 1);
    assert.equal(boardExport.collections[0].kind, 'flows');
    assert.equal(boardExport.collections[0].title, flowTitle);
    assert.equal(boardExport.collections[0].assetIds.length, 4);
    assert.match(boardExport.collections[0].sourceUrl, /^https:\/\/apps\.apple\.com\//);
    await page.getByRole('link', {name:'Flows', exact:true}).click();
    await page.getByRole('link', {name:'UI elements', exact:true}).click();
    await page.waitForFunction(() => document.querySelector('#title').textContent === 'UI elements');
    assert.equal(await page.locator('.collection-card').count(), 25);
    assert.equal(await page.locator('.collection-elements .collection-previews img').count(), 25);
    assert.equal(await page.locator('#viewer').isVisible(), false);
    await page.getByRole('link', {name:'Screens', exact:true}).click();
    await page.waitForFunction(() => document.querySelector('#title').textContent === 'Screens');
    assert.ok((await page.locator('#coverage').textContent()).includes(`${catalogScreenCount} screenshots`));
    assert.ok((await page.locator('#status').textContent()).includes(`${catalogScreenCount} results`));
    await page.getByRole('link', {name:'UI elements', exact:true}).click();
    await page.waitForFunction(() => document.querySelector('#title').textContent === 'UI elements');
    await page.screenshot({path:(process.env.QA_ARTIFACT_DIR || '/tmp') + '/curation-elements.png',animations:'disabled'});
    await page.locator('.collection-card').first().getByRole('button', {name:/Open/}).click();
    assert.equal(await page.locator('.screen-canvas img').count(), 1);
    assert.match(await page.locator('.screen-context').textContent(), /Reviewed/);
    await page.keyboard.press('Escape');
    await page.locator('#viewer').waitFor({state:'hidden'});
    assert.equal(await page.locator('#viewer').isVisible(), false);
    await page.locator('#search').fill('tab bar');
    assert((await page.locator('.collection-card').count()) > 0);
    const [download] = await Promise.all([page.waitForEvent('download'), page.locator('#export').click()]);
    const exported = JSON.parse(require('node:fs').readFileSync(await download.path(), 'utf8'));
    assert.equal(exported.route, 'elements');
    assert.equal(exported.records[0].screenId.length, 64);
    const malformed = await browser.newPage();
    await catalogBase(malformed);
    await malformed.route('**/curation.json', route => route.fulfill({contentType:'application/json',body:JSON.stringify({flows:[null,{id:'bad',title:'Bad',assetIds:{}}],elements:[null]})}));
    await malformed.goto(base + '#apps');
    await malformed.locator('.app-open').first().waitFor();
    assert((await malformed.locator('.app-open').count()) > 0);
    const failed = await browser.newPage();
    await catalogBase(failed);
    await failed.route('**/curation.json', route => route.fulfill({status:503,body:'Unavailable'}));
    await failed.goto(base + '#flows');
    await failed.getByText('These references could not load.').waitFor();
    assert.equal(await failed.locator('#export').isEnabled(), false);
    await failed.unroute('**/curation.json');
    await failed.getByRole('button',{name:'Try again'}).click();
    await failed.locator('.collection-card').first().waitFor();
    assert.equal(await failed.locator('.collection-card').count(),7);
    await failed.close();
    console.log('PASS: curation collections, ordered modal annotation, screen actions, saved flow metadata, search, export');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
